services:
  # Laravel Application
  app:
    env_file: .env.docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestion-scolarite-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - QUEUE_CONNECTION=database
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - laravel

  # Queue Worker
  queue:
    env_file: .env.docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestion-scolarite-queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - QUEUE_CONNECTION=database
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
    depends_on:
      - redis
      - app
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    networks:
      - laravel

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: gestion-scolarite-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - laravel


networks:
  laravel:
    driver: bridge
